# Generated by Django 3.2.7 on 2021-09-14 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=18, verbose_name='Numer telefonu')),
                ('nip_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Numer nip')),
                ('company_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa firmy')),
                ('company_name_l', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa firmy c.d.')),
                ('company', models.BooleanField(default=False, verbose_name='Profil firmowy?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profil użytkownika',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=128, verbose_name='Ulica')),
                ('house', models.CharField(max_length=8, verbose_name='Nr domu')),
                ('door', models.CharField(blank=True, max_length=8, null=True, verbose_name='Nr lokalu')),
                ('city', models.CharField(max_length=64, verbose_name='Miasto')),
                ('post_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Kod pocztowy')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name_plural': 'Adresy',
                'ordering': ('user_id', '-id'),
            },
        ),
    ]
