# Generated by Django 4.0.3 on 2022-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexalfastamp',
            options={'ordering': ('name',), 'verbose_name_plural': 'Index alfabetyczny'},
        ),
        migrations.AlterField(
            model_name='citys',
            name='index_alfa',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Index alfa'),
        ),
    ]
