# Generated by Django 3.2.7 on 2021-09-21 12:41

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models

import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Nazwa marki"
                    ),
                ),
                (
                    "logo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=0,
                        size=[1280, 960],
                        upload_to="images/categorys/",
                        validators=[web.models.products.file_size],
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="Alternatywny text dla obrazka",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Title dla obrazka",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Brand info"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Marka produktów",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag_desc",
                    models.CharField(
                        max_length=156, verbose_name="Meta description"
                    ),
                ),
                (
                    "tag_title",
                    models.CharField(max_length=70, verbose_name="Title"),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Numer kategorii",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=0,
                        size=[1280, 960],
                        upload_to="images/categorys/",
                        validators=[web.models.products.file_size],
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="Alternatywny text dla obrazka",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Title dla obrazka",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Nazwa kategorii"
                    ),
                ),
                ("text", models.TextField(verbose_name="Opis kategorii")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "on_page",
                    models.BooleanField(
                        default=False, verbose_name="Czy na pierwszej stronie?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy jest dostępny"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kategorie produktów",
                "ordering": ("number", "name"),
            },
        ),
        migrations.CreateModel(
            name="Colors",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=32, verbose_name="Nazwa koloru"
                    ),
                ),
                (
                    "class_text",
                    models.CharField(
                        max_length=32, verbose_name="Text dla koloru klasy"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kolory",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        verbose_name="Rozmiar produktu (wielkość, pojemność, waga)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy jest aktualny"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rozmiary produktów",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="Nazwa magazynu"
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=0,
                        size=[1280, 960],
                        upload_to="images/workplace/",
                        validators=[web.models.products.file_size],
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32,
                        verbose_name="Telefon kontaktowy do magazynu",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=128, verbose_name="Ulica/Osiedle"
                    ),
                ),
                (
                    "home",
                    models.CharField(max_length=8, verbose_name="Numer domu"),
                ),
                (
                    "door",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Numer lokalu",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Kraków", max_length=64, verbose_name="Miasto"
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Kod pocztowy",
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Info",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy jest aktywna"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "google_maps_link",
                    models.TextField(
                        blank=True, null=True, verbose_name="Link z mapy google"
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link do facebook"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Magazyn",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Vat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.IntegerField(verbose_name="Stawka VAT")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy jest dostępny"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Nazwa produktu"
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(
                        default=1, verbose_name="Ilość produktu na stanie"
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Produkt info"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=0,
                        size=[1280, 960],
                        upload_to="images/products/",
                        validators=[web.models.products.file_size],
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        max_length=125,
                        verbose_name="Alternatywny text dla obrazka",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Title dla obrazka",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Cena podstawowa",
                    ),
                ),
                (
                    "price_promo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        null=True,
                        verbose_name="Cena promocyjna",
                    ),
                ),
                (
                    "price_netto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        null=True,
                        verbose_name="Cena netto",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy jest dostępny"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.brand",
                        verbose_name="Marka produktu",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.category",
                        verbose_name="Kategoria produktu",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.colors",
                        verbose_name="Kolor produktu",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.size",
                        verbose_name="Rozmiar",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.store",
                        verbose_name="Magazyn",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.vat",
                        verbose_name="Stawka VAT",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produkty",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=0,
                        size=[1280, 960],
                        upload_to="images/",
                        validators=[web.models.products.file_size],
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="Alternatywny text dla obrazka",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Title dla obrazka",
                    ),
                ),
                (
                    "main",
                    models.BooleanField(
                        default=False, verbose_name="Zdjęcie główne"
                    ),
                ),
                (
                    "stamp",
                    models.BooleanField(
                        default=False, verbose_name="Zdjęcie wzornika?"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_gallery",
                        to="web.category",
                        verbose_name="Zdjęcia kategorii",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_gallery",
                        to="web.products",
                        verbose_name="Zdjęcie produktu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Galeria",
                "ordering": ("-id", "image"),
            },
        ),
    ]
