# Generated by Django 4.0.3 on 2022-06-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_indexalfastamp_options_alter_citys_index_alfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citys',
            name='index_alfa',
        ),
        migrations.AddField(
            model_name='citys',
            name='alphabetical_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.indexalfastamp', verbose_name='alphabetical_index'),
        ),
    ]
