# Generated by Django 3.2.7 on 2022-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subcategory_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta title dla kategorii'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description dla kategorii'),
        ),
    ]
