# Generated by Django 3.2.7 on 2022-03-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220315_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternatywny text dla obrazka'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title dla obrazka'),
        ),
        migrations.AddField(
            model_name='articles',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description dla artykułu'),
        ),
        migrations.AddField(
            model_name='articles',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta title dla artykułu'),
        ),
    ]
