# Generated by Django 3.2.7 on 2021-09-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210921_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcopy',
            name='color_text',
        ),
    ]
