# Generated by Django 3.2.7 on 2022-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220316_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_promo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Czy jest w propozycjach'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Czy jest w rekomendowanych'),
        ),
    ]
