# Generated by Django 3.2.7 on 2021-09-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.AddField(
            model_name="products",
            name="sub_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.subcategory",
                verbose_name="PodKategoria produktu",
            ),
            preserve_default=False,
        ),
    ]
