# Generated by Django 3.2.7 on 2022-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20220317_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorytype',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta description dla podkategorii'),
        ),
        migrations.AddField(
            model_name='subcategorytype',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta title dla podkategorii'),
        ),
    ]
