# Generated by Django 3.2.7 on 2021-09-23 08:34

import django.db.models.deletion
from django.db import migrations, models

import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20210922_0717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                upload_to="images/", validators=[web.models.products.file_size]
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/products/",
                validators=[web.models.products.file_size],
                verbose_name="Zdjęcie główne",
            ),
        ),
        migrations.CreateModel(
            name="SubCategoryType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        verbose_name="Nazwa rodzaje produktu w podkategorii",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Numer wyświetlania",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/categorys/",
                        validators=[web.models.products.file_size],
                        verbose_name="Zdjęcie główne",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        max_length=125,
                        null=True,
                        verbose_name="Alternatywny text dla obrazka",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Title dla obrazka",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.subcategory",
                        verbose_name="Rodzaje produktów w podkategorii",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rodzaje produktów w podkategori",
                "ordering": ("number", "name"),
            },
        ),
    ]
