# Generated by Django 3.2.7 on 2021-09-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_auto_20210923_0834"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="products",
            name="sub_category_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.subcategorytype",
                verbose_name="Typ produktu",
            ),
            preserve_default=False,
        ),
    ]
