# Generated by Django 3.2.7 on 2022-03-18 12:50

from django.db import migrations
import django_resized.forms
import web.models.images
import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_images_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[800, 600], upload_to='images/gallery/', validators=[web.models.images.file_size], verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[800, 600], upload_to='images/products/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
    ]
