# Generated by Django 3.2.7 on 2021-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210923_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'ordering': ('-number',), 'verbose_name_plural': 'Rodzaje dostawy'},
        ),
        migrations.AlterModelOptions(
            name='paymethod',
            options={'ordering': ('-number',), 'verbose_name_plural': 'Rodzaje płatności'},
        ),
        migrations.AddField(
            model_name='images',
            name='carousel',
            field=models.BooleanField(default=False, verbose_name='Zdjęcie na karuzele?'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
