# Generated by Django 3.2.7 on 2022-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20220318_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='override_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nadpisana data faktury'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='override_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nadpisany numer faktury'),
        ),
    ]
