# Generated by Django 3.2.7 on 2022-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20220331_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activatetoken',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Token aktywacyjny'},
        ),
        migrations.AddField(
            model_name='products',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Czy jest w top'),
        ),
    ]
