# Generated by Django 3.2.7 on 2022-04-08 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nip_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Numer nip'),
        ),
    ]
