# Generated by Django 3.2.7 on 2022-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_profile_nip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='class_text',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Text dla koloru klasy'),
        ),
    ]
