# Generated by Django 4.0.3 on 2022-04-16 08:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_colors_class_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nazwa miejscowości')),
                ('rybna_area', models.BooleanField(default=False, verbose_name='Okolica Rybnej')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
