# Generated by Django 3.2.7 on 2021-10-01 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_auto_20211001_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="created_time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="modified_time",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
