# Generated by Django 4.0.3 on 2022-04-17 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_colors_class_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_alfa', models.CharField(blank=True, max_length=256, null=True, verbose_name='Index alfa')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nazwa miejscowości')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, verbose_name='Slug')),
                ('rybna_area', models.BooleanField(default=False, verbose_name='Okolica Rybnej')),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Miasta',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IndexAlfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nazwa miejscowości')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, verbose_name='Slug')),
                ('city_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_five', to='web.citys')),
                ('city_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_four', to='web.citys')),
                ('city_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_one', to='web.citys')),
                ('city_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_three', to='web.citys')),
                ('city_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_two', to='web.citys')),
            ],
            options={
                'verbose_name_plural': 'Index alpfa',
                'ordering': ('name',),
            },
        ),
    ]
