# Generated by Django 3.2.7 on 2021-10-06 11:58

from django.db import migrations, models
import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_activatetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/categorys/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categorys/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
    ]
