# Generated by Django 3.2.7 on 2021-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20211006_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Opis podkategorii'),
        ),
    ]
