# Generated by Django 3.2.7 on 2021-10-06 19:35

from django.db import migrations
import django_resized.forms
import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_subcategory_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category', 'number', 'name'), 'verbose_name_plural': 'PodKategorie produktów'},
        ),
        migrations.AlterModelOptions(
            name='subcategorytype',
            options={'ordering': ('sub_category', 'number', 'name'), 'verbose_name_plural': 'Rodzaje produktów w podkategori'},
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 960], upload_to='images/products/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
    ]
