# Generated by Django 3.2.7 on 2021-10-06 19:46

from django.db import migrations
import django_resized.forms
import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20211006_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[1280, 960], upload_to='images/categorys/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[1280, 960], upload_to='images/products/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[1280, 960], upload_to='images/workplace/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
    ]
