# Generated by Django 3.2.7 on 2021-10-07 13:24

from django.db import migrations
import django_resized.forms
import web.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20211006_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymethod',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[1280, 960], upload_to='images/products/', validators=[web.models.products.file_size], verbose_name='Zdjęcie główne'),
        ),
    ]
