# Generated by Django 3.2.7 on 2021-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_paymethod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymethod',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do regulaminu'),
        ),
    ]
