# Generated by Django 3.2.7 on 2021-10-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_paymethod_pay_method'),
        ('web', '0023_auto_20211008_1039'),
    ]

    operations = [
    ]
