# Generated by Django 3.2.7 on 2021-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20211008_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='main_status',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Potwierdzone'), (3, 'Zapłacone'), (4, 'Zrealizowane')], default=1, verbose_name='Status zamówienia'),
        ),
    ]
