# Generated by Django 3.2.7 on 2021-10-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_merge_20211008_1042"),
        ("web", "0024_orders_main_status"),
    ]

    operations = []
