# Generated by Django 3.2.7 on 2022-01-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_merge_20211012_2257"),
        ("web", "0027_auto_20220120_1744"),
    ]

    operations = []
