# Generated by Django 3.2.7 on 2022-02-13 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_articles_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('number', models.CharField(max_length=120)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
            options={
                'verbose_name_plural': 'Faktury',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.invoices', verbose_name='Faktura'),
        ),
    ]
