# Generated by Django 3.2.7 on 2022-02-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_orders_prodcuts_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="prodcuts_item",
            new_name="products_item",
        ),
    ]
