# Generated by Django 3.2.7 on 2022-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_rename_prodcuts_item_orders_products_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pdf',
            new_name='invoice_created',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='invoice',
            new_name='pdf_created',
        ),
        migrations.AlterField(
            model_name='orders',
            name='main_status',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Do zapłaty'), (3, 'Zapłacone')], default=1, verbose_name='Status zamówienia'),
        ),
    ]
