# Generated by Django 3.2.7 on 2022-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20220217_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='price_netto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Cena netto'),
        ),
    ]
