# Generated by Django 3.2.7 on 2022-02-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_deliverymethod_price_netto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoices',
            options={'ordering': ('-created_time',), 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='invoice_created',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.invoices', verbose_name='Faktura'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='main_status',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Do zapłaty'), (3, 'Zapłacone')], default=1, verbose_name='Status płatności'),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='pay_method',
            field=models.IntegerField(choices=[(1, 'gotówka'), (2, 'karta'), (3, 'przelew'), (4, 'przelew p24')], verbose_name='Rodzaj płatności'),
        ),
    ]
