# Generated by Django 3.2.7 on 2022-03-03 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_invoices_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Profil użytkownika'},
        ),
        migrations.AlterField(
            model_name='invoices',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternatywny text dla obrazka'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nip_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Numer nip'),
        ),
    ]
