# Generated by Django 3.2.7 on 2022-03-03 18:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0037_invoices_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Profil użytkownika'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='invoice_created',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='main_status',
            new_name='pay_status',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pdf_created',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoices',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinet_id', to='auth.user', verbose_name='Klient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.deliverymethod', verbose_name='Rodzaj dostawy'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.paymethod', verbose_name='Rodzaj płatności'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Otwarte'), (2, 'W przygotowaniu'), (3, 'W dostawie'), (4, 'Gotowe do odbioru'), (5, 'Zrealizowane'), (6, 'Anulowane')], default=1, verbose_name='Status zamówienia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nip_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Numer nip'),
        ),
    ]
