# Generated by Django 3.2.7 on 2022-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20220303_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='invoice_true',
            field=models.BooleanField(default=False, verbose_name='Czy wybrano fakturę'),
        ),
    ]
