# Generated by Django 3.2.7 on 2022-03-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20220303_1514'),
        ('web', '0039_orders_invoice_true'),
    ]

    operations = [
    ]
