# Generated by Django 3.2.7 on 2022-03-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_merge_20220303_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(default=1, max_length=6, verbose_name='Kod pocztowy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoices',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.orders'),
        ),
    ]
