# Generated by Django 3.2.7 on 2022-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20220304_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Id płatności w Stripe'),
        ),
    ]
