# Generated by Django 3.2.7 on 2022-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_orders_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_success',
            field=models.BooleanField(default=False, verbose_name='Elektroniczna płatność udana'),
        ),
    ]
